trigger:
  batch: true
  branches:
    include:
    - master
    - production
    
pr:
  branches:
    include:
    - master
    - production
    
variables:
  # Cannot use key:value syntax in root defined variables
  - name: _TeamName
    value: DotNetCore

jobs:
- template: /eng/common/templates/jobs/jobs.yml
  parameters:
    enablePublishBuildArtifacts: true
    enableTelemetry: true
    graphFileGeneration:
      enabled: true
      includeToolset: true
    helixRepo: dotnet/arcade-pool-provider
    jobs:
    - job: Windows_NT
      timeoutInMinutes: 90
      pool:
        # For public or PR jobs, use the hosted pool.  For internal jobs use the internal pool.
        # Will eventually change this to two BYOC pools.
        ${{ if or(eq(variables['System.TeamProject'], 'public'), in(variables['Build.Reason'], 'PullRequest')) }}:
          name: NetCorePublic-Pool
          queue: BuildPool.Windows.10.Amd64.VS2017.Open
        ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
          name: NetCoreInternal-Pool
          queue: BuildPool.Windows.10.Amd64.VS2017
      variables:
      - _Script: eng\common\cibuild.cmd

      strategy:
        matrix:
          Build_Release:
            _BuildConfig: Release
          ${{ if or(eq(variables['System.TeamProject'], 'public'), in(variables['Build.Reason'], 'PullRequest')) }}:
            Build_Debug:
              _BuildConfig: Debug
      steps:
      - checkout: self
        clean: true
      # Use utility script to run script command dependent on agent OS.
      - script: eng\common\cibuild.cmd
          -configuration $(_BuildConfig) 
          -prepareMachine
          /p:Test=false
        displayName: Windows Build / Publish